<?php
/**
 * Auto generated by prado-cli.php on 2013-05-14 02:37:24.
 */
class imagenRecord extends TActiveRecord
{
	const TABLE='imagen';

	public $ID_IMAGEN;
	public $RUTA_IMAGEN;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>