<?php
/**
 * Auto generated by prado-cli.php on 2013-05-14 02:39:18.
 */
class solicitudRecord extends TActiveRecord
{
	const TABLE='solicitud';

	public $ID_SOLICITUD;
	public $ID_ARTICULO;
	public $ID_USUARIO;
	public $USU_ID_USUARIO;
	public $ART_ID_ARTICULO;
	public $MENSAJE;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>