<?php
/**
 * Auto generated by prado-cli.php on 2013-05-14 03:16:20.
 */
class ubicacionRecord extends TActiveRecord
{
	const TABLE='ubicacion';

	public $ID_UBICACION;
	public $CIUDAD;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static function consultarCiudades(){
		
		$connection=new TDbConnection();
		$connection->setConnectionString("mysql:host=localhost;dbname=trueque");
		$connection->setUsername("root");
		$connection->setPassword("46081098");
		
		$connection->Active=true; 

		
		$sql="SELECT * FROM ubicacion;  ";
		$dataReader=$connection->createCommand($sql)->query();
	
		$connection->Active=false;
		
		$dataReader->bindColumn(2,$ca);
		$dataReader->bindColumn(1,$id);
		$i=0;
		
		while($dataReader->read()!==false)
		{
			$a['id']=$id;
			$a['ciudad']=utf8_encode($ca);
			$b[$i]=$a;
			$i=$i+1;
		}
		
		return $b;
		
	}
}
?>