<?php
/**
 * Auto generated by prado-cli.php on 2013-05-14 02:39:18.
 */
class solicitudRecord extends TActiveRecord
{
	const TABLE='solicitud';

	public $ID_SOLICITUD;
	public $ID_ARTICULO;
	public $ID_USUARIO;//quien envia la solicitud
	public $USU_ID_USUARIO;//a quien se le envia la solicitud
	public $ART_ID_ARTICULO;
	public $MENSAJE;
	public $FECHA_PROPUESTA;
	public $FECHA_RESPUESTA;
	public $ESTADO;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static function ObtenerPermutas($desde,$hasta,$consulta){
	    $connection=new TDbConnection();
		$connection->setConnectionString("mysql:host=localhost;dbname=trueque");
		$connection->setUsername("root");
		$connection->setPassword("46081098");
		if($consulta='todas'){
			$sql="SELECT CATEGORIA , COUNT(ID_SOLICITUD) FROM solicitud  NATURAL JOIN  articulo 
				WHERE  FECHA_PROPUESTA
				BETWEEN ' $desde'
				AND  '$hasta'
				GROUP BY  CATEGORIA";
		}
		
		
		
		
		$connection->Active=true;
		$dataReader=$connection->createCommand($sql)->query();
		$connection->Active=false;
		$dataReader->bindColumn(2,$ca);
		$dataReader->bindColumn(1,$id);
		$i=0;
		$b=null;
			while($dataReader->read()!==false)
			{
				$a['CATEGORIA']=utf8_encode($id);
				$a['NUMERO']=$ca;
				$b[$i]=$a;
				$i=$i+1;
			}
		if($b!=null){	
			return $b;
		}else{
			return null;
		}
		
	}
}
?>