<?php
/**
 * Auto generated by prado-cli.php on 2013-05-14 02:37:50.
 */
class usuarioRecord extends TActiveRecord
{
	const TABLE='usuario';

	public $ID_USUARIO;
	public $ID_UBICACION;
	public $NOMBRE_USUARIO;
	public $APELLIDO_USUARIO;
	public $FECHA_N;
	public $TELEFONO;
	public $PREGUNTA;
	public $RESPUESTA;
	public $CORREO;
	public $NICK;
	public $PASS;
	public $tipo;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	
}
?>